### ISSUE TITLE
Trello logo bug in firefox

### ISSUE THREAD

**Issue by johnellison** [sprky/sprky_chess#101]
![screen shot 2015-04-12 at 2 05 19 pm](https://cloud.githubusercontent.com/assets/5806135/7107257/2aa6d344-e11d-11e4-8bc4-26b5605538af.png)

**Comment by washburnad** [comment]
Firefox seems to be displaying all of the logos in their native dimensions, which for the trello logo is about 2600px wide. 

```
  .tool-item {
    img {
      width: 100%;
      height: 100%;
    }
  }
```

This solves the problem in firefox but scrunches them up in Chrome. - 4 on the first line, just rubocop on the second line.
