### ISSUE TITLE
Initialize game doesn't populate game_id

### ISSUE THREAD

**Issue by washburnad** [sprky/sprky_chess#12]
When a game is initialized all of the game_id attributes for the pieces are nil.  

From a web search it looks like the problem is that 
```def initialize_board!```
is a class method rather than an instance method, so self.id doesn't have a value.  Do we solve this by making the method an instance method or by passing (@game) as a variable to the class method?

**Comment by kenmazaika** [comment]
Good catch.

Yeah, the problem is using the `before_create` is before the game has an `id` set.  We probably will want to use `after_create` instead, so that `id` gets passed along.

Let's also add a unit test to make sure it works as expected.

**Comment by hsinkoff** [comment]
I just added a pull request with changes that address this issue.
