### ISSUE TITLE
Checkmate method still has a glitch

### ISSUE THREAD

**Issue by washburnad** [sprky/sprky_chess#120]
Playing out a game I found that if the king was in check there were still instances where the checkmate moves didn't undo (e.g. the king captured a pawn who had him in check)

**Comment by johnellison** [comment]
I also just experienced a bug when trying to test for pawn promotion. I had a pawn advance to the point of moving the king into check, and as soon as the game state turned to check the pawn vanished off the board...

**Comment by washburnad** [comment]
Yes, the king probably captured it. I can't figure out where the 'hole' is in the transactions but it seems to be in the king trying to move self out of check.

**Comment by johnellison** [comment]
You fixed this, right? Can we close it?
