### ISSUE TITLE
Fix Pawn legal_move? logic

### ISSUE THREAD

**Issue by johnellison** [sprky/sprky_chess#23]
- @washburnad commented on app/models/pawn.rb in f446a7b "if it's not a diagonal attack we also need to discount all horizontal movement and immediately return false"
- @washburnad commented on  app/models/pawn.rb in f446a7b" this will allow a pawn to move in either direction, right? Instead of absolute value we want something like
`10. vertical_diff = (y-self.y_position)`
`20. return vertical_diff == 1 && color || vertical_diff == -1 && !color.  # 1 & white or -1 and black`"

**Comment by washburnad** [comment]
I've started work on this.

**Comment by johnellison** [comment]
I had a feeling you were going to come along and save my messy code ;)

John Ellison

303-358-7594
jbellison@icloud.com
john-ellison.com <http://ohn-ellison.com/>
@iamjohnellison <http://www.twitter.com/iamjohnellison>

Be who you were born to be.
