### ISSUE TITLE
Scope and Use of obstructed_move?

### ISSUE THREAD

**Issue by johnellison** [sprky/sprky_chess#38]
I noticed we're not calling `obstructed_move?` inside `legal_move?` for each individual piece type. 

How do we integrate the two as an application wide protocol? Will we check to see if the move is obstructed while inside `legal_move?` or is the obstructed move called at a different level in the application?

the way we're testing `obstructed_move?` now is with a public method. Should the obstructed move for each piece type in fact be private, only to be called upon within the piece type model?

**Comment by washburnad** [comment]
I think this is a great conversation to have and is related to the flow chart conversation.  I personally think legal move and obstructed move are different, but both could be called from within valid move.

**Comment by washburnad** [comment]
I move to close this conversation as the new valid_move logic takes this into consideration.
