### ISSUE TITLE
Fix pawn capture bug

### ISSUE THREAD

**Issue by johnellison** [sprky/sprky_chess#61]
This test in piece_test.rb fails (not a capture_move):

`  test "should move to and capture" do
    game = FactoryGirl.create(:game)
    white_pawn = FactoryGirl.create(:pawn, x_position: 1, y_position: 3, color: true, game_id: game.id)
    black_pawn = FactoryGirl.create(:pawn, x_position: 2, y_position: 4, color: false, game_id: game.id)
    
    white_pawn.move_to(white_pawn, {x_position: 2, y_position: 4})

    assert white_pawn.capture_move?(2, 4), 'capture move'
    assert_equal 2, white_pawn.x_position
    assert_equal 4, white_pawn.y_position

    assert black_pawn.captured?, 'captured black pawn'
  end`

even though this test in pawn_test.rb passes: 

` test "should capture" do
    game = FactoryGirl.create(:game)
    white_pawn = FactoryGirl.create(:pawn, x_position: 1, y_position: 3, color: true, game_id: game.id)
    black_pawn = FactoryGirl.create(:pawn, x_position: 2, y_position: 4, color: false, game_id: game.id)
    assert white_pawn.capture_move?(2, 4)
  end`

It has something to do with the move_to method call: 

` def move_to(piece, params)
    x = params[:x_position].to_i
    y = params[:y_position].to_i

    if piece.valid_move?(x, y)
      piece.update_attributes(params)
      if capture_move?(x, y)
        captured = game.obstruction(x,y)
        captured.mark_captured
      end
    end
  end`

which calls capture_move? on pawn returns false.

**Comment by washburnad** [comment]
In the piece test you are implementing the move_to before testing capture_move?  After move_to the white_pawn is in the destination location so you're y_diff and x_diff are wrong.

**Comment by washburnad** [comment]
pushed branch - notes in files
