### ISSUE TITLE
Board squares collapsing/oversized in firefox

### ISSUE THREAD

**Issue by washburnad** [sprky/sprky_chess#74]
Squares are 100x100 (size of symbol image).
Squares without an image collapse to 60px high.

**Comment by johnellison** [comment]
I think we can close this issue:

![image](https://cloud.githubusercontent.com/assets/5806135/7104343/a368bb30-e096-11e4-82b0-dca8edb64737.png)

**Comment by washburnad** [comment]
The new SVGs aren't loading for me on Heroku in either Firefox or Chrome - still loads the 100x100 gifs

**Comment by johnellison** [comment]
You have to create a new game for the new piece images to be loaded.
